service:
  name: poc-ts-decorators

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  app:
    handler: src/api/controller.getValuation
    events:
      - http:
          path: /valuation
          method: GET
          cors: true
      - http:
          path: /{version}/valuation
          method: GET
          cors: true

