service:
  name: poc-ts-decorators

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  app:
    handler: api/endpoints.getValuation

